import test from "node:test";
import assert from "node:assert/strict";
import { createHarness } from "./helpers/lite.mjs";

// Supabase sends the union of bulk-row keys as ?columns= and maps
// defaultToNull:false to Prefer: missing=default. PostgREST semantics:
// https://docs.postgrest.org/en/v14/references/api/preferences.html#missing
// https://github.com/PostgREST/postgrest/blob/v14.5/src/PostgREST/Query/QueryBuilder.hs#L112-L130
const ddl = `
  CREATE TABLE items (id integer PRIMARY KEY, score integer DEFAULT 100,
    memo text DEFAULT 'kept');
  CREATE TABLE required (id integer PRIMARY KEY, score integer NOT NULL DEFAULT 100);
  CREATE TABLE generated (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text, token uuid DEFAULT gen_random_uuid(), payload jsonb DEFAULT '{"ok":true}'::jsonb);
  CREATE TABLE conflicts (id integer PRIMARY KEY, slug text UNIQUE, score integer DEFAULT 100);
  CREATE TABLE composite (org integer, slug text, score integer, PRIMARY KEY (org, slug));
  CREATE SCHEMA extra;
  CREATE TABLE extra.items (id integer PRIMARY KEY, score integer DEFAULT 200);
`;
const ok = (result) => {
  assert.equal(result.error, null, JSON.stringify(result.error));
  return result.data;
};

for (const backend of ["node", "libsql", "pglite"]) {
  test(`${backend}: SDK bulk write semantics`, async (t) => {
    const { client, app, connection, close } = await createHarness({ backend, ddl });
    t.after(close);
    app.config.api.schemas = ["public", "extra"];
    let inserts = 0;
    const insertQueries = new WeakSet();
    connection.kysely = connection.kysely.withPlugin({
      transformQuery({ node, queryId }) {
        if (node.kind === "InsertQueryNode") insertQueries.add(queryId);
        return node;
      },
      async transformResult({ result, queryId }) {
        // Compiling a query also transforms it; count only completed executions.
        if (insertQueries.has(queryId)) inserts++;
        return result;
      },
    });

    for (const operation of ["insert", "upsert"]) {
      for (const defaultToNull of [true, false]) {
        await t.test(`${operation} honors defaultToNull=${defaultToNull}`, async () => {
          ok(await client.from("items").delete().gte("id", 0));
          if (operation === "upsert") {
            ok(await client.from("items").insert([
              { id: 1, score: 11 }, { id: 2, score: 22 }, { id: 3, score: 33 },
            ]));
          }
          inserts = 0;
          const result = await client.from("items")[operation]([
            { id: 1 }, { id: 2, score: 42 }, { id: 3, score: null },
          ], { defaultToNull, count: "exact" }).select("id,score,memo").order("id");
          ok(result);
          assert.equal(result.count, 3);
          assert.equal(inserts, 1, "keep one bulk SQL statement");
          const expected = [
            { id: 1, score: defaultToNull ? null : 100, memo: "kept" },
            { id: 2, score: 42, memo: "kept" },
            { id: 3, score: null, memo: "kept" },
          ];
          const stored = ok(await client.from("items").select("id,score,memo").order("id"));
          assert.deepEqual(stored, expected);
          assert.deepEqual(result.data, stored, "return the stored values, not input-shaped nulls");
        });
      }
    }

    await t.test("database defaults and returned aliases survive reordered rows", async () => {
      ok(await client.from("items").delete().gte("id", 0));
      const rows = ok(await client.from("items").insert([
        { id: 2, score: 42 }, { id: 1 },
      ], { defaultToNull: false }).select("id,actual:score").order("id"));
      assert.deepEqual(rows, [{ id: 1, actual: 100 }, { id: 2, actual: 42 }]);
      const minimal = await client.from("items").insert([
        { id: 3 }, { id: 4, score: 7 },
      ], { defaultToNull: false, count: "exact" });
      ok(minimal);
      assert.equal(minimal.data, null);
      assert.equal(minimal.count, 2);
      assert.deepEqual(ok(await client.from("items").select("id,score").gte("id", 3).order("id")),
        [{ id: 3, score: 100 }, { id: 4, score: 7 }]);
    });

    await t.test("identity and expression defaults are evaluated in the database", async () => {
      const supplied = "00000000-0000-4000-8000-000000000001";
      ok(await client.from("generated").insert({ id: 10, label: "original" }));
      const rows = ok(await client.from("generated").upsert([
        { id: 10, label: "updated", token: supplied, payload: { explicit: true } },
        { label: "new" },
        { label: "another" },
      ], { defaultToNull: false }).select().order("label"));
      assert.equal(rows.length, 3);
      assert.equal(new Set(rows.map((row) => row.id)).size, 3);
      assert.equal(new Set(rows.map((row) => row.token)).size, 3);
      for (const row of rows) {
        assert.match(row.token, /^[0-9a-f-]{36}$/);
        assert.deepEqual(row.payload, row.id === 10 ? { explicit: true } : { ok: true });
      }
      assert.equal(rows.find((row) => row.id === 10).token, supplied);
      assert.deepEqual(rows, ok(await client.from("generated").select().order("label")));
    });

    await t.test("defaults belong to the explicitly selected schema", async () => {
      for (const operation of ["insert", "upsert"]) {
        const rows = ok(await client.schema("extra").from("items")[operation]([
          { id: 1 }, { id: 2, score: 42 },
        ], { defaultToNull: false }).select().order("id"));
        assert.deepEqual(rows, [{ id: 1, score: 200 }, { id: 2, score: 42 }]);
        assert.deepEqual(rows, ok(await client.schema("extra").from("items").select().order("id")));
      }
    });

    await t.test("explicit columns filters keys and fills requested missing columns", async (t) => {
      if (backend !== "pglite") {
        const schema = connection.config.translation.deparse.schema.get("public.items");
        for (const name of ["score", "memo"]) {
          const context = schema.get(name).context;
          const previous = context.defaultFn;
          context.defaultFn = () => name === "score" ? 777 : "synthetic";
          t.after(() => { context.defaultFn = previous; });
        }
      }
      for (const missing of ["null", "default"]) {
        const id = missing === "null" ? 5 : 6;
        const response = await app.fetch(new Request("http://localhost/rest/v1/items?columns=id,score", {
          method: "POST",
          headers: { "Content-Type": "application/json", Prefer: `missing=${missing},return=representation` },
          body: JSON.stringify({ id, memo: "ignored", unknown: "ignored" }),
        }));
        assert.equal(response.status, 201);
        assert.deepEqual(await response.json(), [{ id, score: missing === "null" ? null : 100, memo: "kept" }]);
      }
    });

    await t.test("NOT NULL defaults work and failed batches remain atomic", async (t) => {
      t.mock.method(console, "error", () => {});
      ok(await client.from("required").insert([
        { id: 1 }, { id: 2, score: 42 },
      ], { defaultToNull: false }));
      assert.deepEqual(ok(await client.from("required").select().order("id")),
        [{ id: 1, score: 100 }, { id: 2, score: 42 }]);
      for (const operation of ["insert", "upsert"]) {
        for (const defaultToNull of [true, false]) {
          const failure = await client.from("required")[operation]([
            { id: operation === "upsert" ? 1 : 3, score: 99 },
            defaultToNull ? { id: 4 } : { id: 4, score: null },
          ], { defaultToNull });
          assert.notEqual(failure.error, null, "missing=null and explicit null must violate NOT NULL");
          assert.deepEqual(ok(await client.from("required").select().order("id")),
            [{ id: 1, score: 100 }, { id: 2, score: 42 }]);
        }
      }
    });

    await t.test("unique and composite targets plus ignoreDuplicates keep working", async () => {
      ok(await client.from("conflicts").insert({ id: 1, slug: "old", score: 11 }));
      assert.deepEqual(ok(await client.from("conflicts").upsert(
        { id: 2, slug: "old", score: 22 }, { onConflict: "slug" },
      ).select()), [{ id: 2, slug: "old", score: 22 }]);
      const ignored = await client.from("conflicts").upsert([
        { id: 2, slug: "old" }, { id: 3, slug: "new", score: 33 },
      ], { onConflict: "slug", ignoreDuplicates: true, count: "exact" }).select();
      assert.deepEqual(ok(ignored), [{ id: 3, slug: "new", score: 33 }]);
      assert.equal(ignored.count, 1);
      assert.equal(ok(await client.from("conflicts").select("score").eq("id", 2))[0].score, 22);
      ok(await client.from("composite").insert({ org: 1, slug: "a", score: 1 }));
      assert.deepEqual(ok(await client.from("composite").upsert([
        { org: 1, slug: "a", score: 2 }, { org: 2, slug: "a", score: 3 },
      ], { onConflict: "org,slug" }).select().order("org")),
      [{ org: 1, slug: "a", score: 2 }, { org: 2, slug: "a", score: 3 }]);
    });
  });
}
