import assert from "node:assert/strict";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { createHarness } from "./helpers/lite.mjs";
import * as candidate from "../upstream/lite-0.11.0/dist/cli/index.js";
import { replay } from "./helpers/upgrade-identity.mjs";

const ddl = `
CREATE TABLE z_identity_always (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  doubled bigint GENERATED ALWAYS AS (id * 2) STORED
);
CREATE TABLE a_identity_child (
  id serial PRIMARY KEY,
  parent_id bigint NOT NULL REFERENCES z_identity_always(id),
  label text
);
CREATE TABLE identity_default (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label text);
CREATE TABLE ordinary_record (id integer PRIMARY KEY, label text);
`;
const errorCode = code => error => error.code === code;

async function populated(t, backend) {
  // After-hooks outlive each test; release the closed fixture they capture.
  let source = await createHarness({ backend, ddl });
  t.after(async () => { try { await source.close(); } finally { source = null; } });
  for (const [table, row] of [
    ["z_identity_always", { label: "existing" }],
    ["a_identity_child", { parent_id: 1, label: "related" }],
    ["identity_default", { label: "default existing" }],
    ["ordinary_record", { id: 7, label: "plain" }],
  ]) {
    const response = await source.client.from(table).insert(row).select();
    assert.equal(response.error, null, JSON.stringify(response.error));
    assert.equal(response.data[0].id, table === "ordinary_record" ? 7 : 1);
  }
  return source;
}

for (const backend of ["node", "pglite"]) {
  test(`${backend}: omitting identity override and sequence reset reproduces PostgreSQL failures`, async t => {
    const source = await populated(t, backend);
    const groups = await candidate.exportUserData(source.app, { sql: ddl });
    let target = new PGlite();
    t.after(async () => { try { await target.close(); } finally { target = null; } });
    await target.exec(ddl);
    const always = groups.find(group => group.table === "z_identity_always");
    const byDefault = groups.find(group => group.table === "identity_default");
    await assert.rejects(target.exec(always.inserts[0].replace(" OVERRIDING SYSTEM VALUE", "")), errorCode("428C9"));
    await replay(target, [{ ...byDefault, sequenceResets: [] }]);
    await assert.rejects(target.exec("INSERT INTO identity_default(label) VALUES ('next')"), errorCode("23505"));
  });

  test(`candidate ${backend} exporter preserves identity IDs, FK, computed values and next inserts`, async t => {
    const source = await populated(t, backend);
    const groups = await candidate.exportUserData(source.app, { sql: ddl });
    let target = new PGlite();
    t.after(async () => { try { await target.close(); } finally { target = null; } });
    await target.exec(ddl);
    assert.ok(groups.findIndex(g => g.table === "z_identity_always") < groups.findIndex(g => g.table === "a_identity_child"));
    for (const group of groups) {
      for (const insert of group.inserts) {
        assert.equal(insert.includes("OVERRIDING SYSTEM VALUE"), group.table === "z_identity_always");
        assert.ok(!insert.includes('"doubled"'));
      }
      assert.equal(group.sequenceResets.length, group.table === "ordinary_record" ? 0 : 1);
    }
    // The serial path and SQL are intentionally unchanged by this identity fix.
    assert.equal(groups.find(g => g.table === "a_identity_child").sequenceResets[0],
      `SELECT setval(pg_get_serial_sequence('"public"."a_identity_child"', 'id'), COALESCE((SELECT MAX("id") FROM "public"."a_identity_child"), 1));`);
    await replay(target, groups);
    assert.deepEqual((await target.query("SELECT * FROM z_identity_always")).rows,
      [{ id: 1, label: "existing", doubled: 2 }]);
    assert.deepEqual((await target.query("SELECT * FROM a_identity_child")).rows,
      [{ id: 1, parent_id: 1, label: "related" }]);
    assert.deepEqual((await target.query("INSERT INTO z_identity_always(label) VALUES ('next') RETURNING id,doubled")).rows,
      [{ id: 2, doubled: 4 }]);
    assert.deepEqual((await target.query("INSERT INTO identity_default(label) VALUES ('next') RETURNING id")).rows, [{ id: 2 }]);
    assert.deepEqual((await target.query("INSERT INTO a_identity_child(parent_id) VALUES (2) RETURNING id")).rows, [{ id: 2 }]);
    assert.deepEqual((await target.query("SELECT * FROM ordinary_record")).rows, [{ id: 7, label: "plain" }]);
  });
}
