import assert from "node:assert/strict";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { identitySequenceReset } from "../dist/upgrade/identity.js";
import { createHarness } from "./helpers/lite.mjs";
import { exporter, replay } from "./helpers/upgrade-identity.mjs";

const candidate = await exporter();
const errorCode = code => error => error.code === code;

test("reconstruction retains actual identity mode and options after ALTER migrations", async () => {
  const sql = `CREATE TABLE changing (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 3 MINVALUE 10 MAXVALUE 100) PRIMARY KEY);
    ALTER TABLE changing ALTER COLUMN id SET GENERATED ALWAYS;
    CREATE TABLE no_longer_identity(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY);
    ALTER TABLE no_longer_identity ALTER COLUMN id DROP IDENTITY;`;
  const reconstructed = await candidate.reconstructSchema(sql);
  assert.match(reconstructed, /GENERATED ALWAYS AS IDENTITY \(START WITH 10 INCREMENT BY 3 MINVALUE 10 MAXVALUE 100 NO CYCLE\)/);
  const schema = await candidate.upgradeSchema({ sql });
  assert.equal(schema.get("public.changing").get("id").context.identityGeneration, "ALWAYS");
  assert.equal(schema.get("public.changing").get("id").context.isSerial, true);
  assert.equal(schema.get("public.no_longer_identity").get("id").context.identityGeneration, undefined);
});

test("PGlite source custom direction, bounds, increments and empty identity replay", async t => {
  const sql = `
    CREATE TABLE ascending_identity(id bigint GENERATED BY DEFAULT AS IDENTITY (START 10 INCREMENT 3 MINVALUE 10 MAXVALUE 100) PRIMARY KEY);
    CREATE TABLE descending_identity(id bigint GENERATED ALWAYS AS IDENTITY (START -5 INCREMENT -2 MINVALUE -99 MAXVALUE -1) PRIMARY KEY);
    CREATE TABLE empty_identity(id bigint GENERATED BY DEFAULT AS IDENTITY (START 10 INCREMENT 3 MINVALUE 10 MAXVALUE 100) PRIMARY KEY);
    CREATE TABLE exhausted_ascending(id bigint GENERATED BY DEFAULT AS IDENTITY (START 10 INCREMENT 3 MINVALUE 10 MAXVALUE 13) PRIMARY KEY);
    CREATE TABLE exhausted_descending(id bigint GENERATED BY DEFAULT AS IDENTITY (START -5 INCREMENT -2 MINVALUE -7 MAXVALUE -1) PRIMARY KEY);`;
  const source = await createHarness({ backend: "pglite", ddl: sql }); t.after(() => source.close());
  for (const table of ["ascending_identity", "descending_identity", "exhausted_ascending", "exhausted_descending"]) {
    await source.connection.exec(`INSERT INTO ${table} DEFAULT VALUES; INSERT INTO ${table} DEFAULT VALUES`);
  }
  const groups = await candidate.exportUserData(source.app, { sql });
  assert.ok(!groups.some(group => group.table === "empty_identity"));
  const target = new PGlite(); t.after(() => target.close());
  await target.exec(sql); await replay(target, groups);
  for (const [table, next] of [["ascending_identity", 16], ["descending_identity", -9], ["empty_identity", 10]]) {
    assert.deepEqual((await target.query(`INSERT INTO ${table} DEFAULT VALUES RETURNING id`)).rows, [{ id: next }]);
  }
  for (const table of ["exhausted_ascending", "exhausted_descending"]) {
    await assert.rejects(target.exec(`INSERT INTO ${table} DEFAULT VALUES`), errorCode("2200H"));
  }
});

test("identity reset uses start and aligned increments, handles empty/explicit/out-of-bound IDs and bigint exhaustion", async t => {
  const target = new PGlite(); t.after(() => target.close());
  const cases = [
    ["empty", "START 10 INCREMENT 3 MINVALUE 10 MAXVALUE 100", null, 10],
    ["before_start", "START 10 INCREMENT 3 MINVALUE -100 MAXVALUE 100", "-50", 10],
    ["before_start_fraction", "START 10 INCREMENT 3 MINVALUE -100 MAXVALUE 100", "9", 10],
    ["descending_start_fraction", "START -5 INCREMENT -2 MINVALUE -99 MAXVALUE 100", "-4", -5],
    ["between_steps", "START 10 INCREMENT 3 MINVALUE 10 MAXVALUE 100", "14", 16],
    ["descending_step", "START -5 INCREMENT -2 MINVALUE -99 MAXVALUE -1", "-8", -9],
    ["descending_before_start", "START -5 INCREMENT -2 MINVALUE -99 MAXVALUE 100", "50", -5],
    ["outside_max", "START 10 INCREMENT 3 MINVALUE 10 MAXVALUE 100", "1000", "2200H"],
    ["outside_min", "START -5 INCREMENT -2 MINVALUE -99 MAXVALUE -1", "-1000", "2200H"],
    ["huge_step_up", "START -9223372036854775808 INCREMENT 9223372036854775807 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807", "9223372036854775805", { id: "9223372036854775806" }],
    ["huge_step_down", "START 9223372036854775807 INCREMENT -9223372036854775807 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807", "-9223372036854775806", { id: "-9223372036854775807" }],
    ["bigint_max", "START 9223372036854775806 MINVALUE 1 MAXVALUE 9223372036854775807", "9223372036854775807", "2200H"],
    ["bigint_min", "START -9223372036854775807 INCREMENT -1 MINVALUE -9223372036854775808 MAXVALUE -1", "-9223372036854775808", "2200H"],
  ];
  for (const [table, options, id, expected] of cases) {
    await target.exec(`CREATE TABLE ${table}(id bigint GENERATED BY DEFAULT AS IDENTITY (${options}) PRIMARY KEY)`);
    if (id !== null) await target.exec(`INSERT INTO ${table}(id) VALUES (${id})`);
    await target.exec(identitySequenceReset("public", table, "id"));
    if (typeof expected === "number") assert.deepEqual((await target.query(`INSERT INTO ${table} DEFAULT VALUES RETURNING id`)).rows, [{ id: expected }]);
    else if (typeof expected === "object") assert.deepEqual((await target.query(`INSERT INTO ${table} DEFAULT VALUES RETURNING id::text AS id`)).rows, [expected]);
    else await assert.rejects(target.exec(`INSERT INTO ${table} DEFAULT VALUES`), errorCode(expected));
  }
});

test("nonempty CYCLE identity exports fail explicitly rather than promise collision-free continuation", async t => {
  const sql = "CREATE TABLE cycling(id int GENERATED BY DEFAULT AS IDENTITY (MINVALUE 1 MAXVALUE 2 CYCLE) PRIMARY KEY)";
  const source = await createHarness({ backend: "pglite", ddl: sql }); t.after(() => source.close());
  await source.connection.exec("INSERT INTO cycling DEFAULT VALUES");
  const groups = await candidate.exportUserData(source.app, { sql });
  const target = new PGlite(); t.after(() => target.close()); await target.exec(sql);
  await assert.rejects(replay(target, groups), error => error.code === "0A000" && /does not support CYCLE/.test(error.message));
});

test("identity reset quotes names including its DO delimiter", async t => {
  const target = new PGlite(); t.after(() => target.close());
  const schema = 'odd"schema', table = "table'$lite_identity$", column = 'odd"id';
  const quote = value => `"${value.replace(/"/g, '""')}"`;
  const relation = `${quote(schema)}.${quote(table)}`;
  await target.exec(`CREATE SCHEMA ${quote(schema)}; CREATE TABLE ${relation}(${quote(column)} bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY); INSERT INTO ${relation} DEFAULT VALUES`);
  await target.exec(identitySequenceReset(schema, table, column));
  assert.deepEqual((await target.query(`INSERT INTO ${relation} DEFAULT VALUES RETURNING ${quote(column)}`)).rows, [{ [column]: 2 }]);
});
