project_id = "functions-graduation"

[auth.email]
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "1MiB"

[edge_runtime]
enabled = true
policy = "oneshot"

[functions.tasks]
verify_jwt = true
